version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
