# Generated by Django 5.0.7 on 2024-08-05 01:57

import quack_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quack_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(max_length=30, unique=True, validators=[quack_app.validators.validate_handle]),
        ),
    ]
