# Generated by Django 5.0.7 on 2024-08-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quack_app', '0007_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/profile_default.jpg', upload_to='profile_pics/'),
        ),
    ]
