# Generated by Django 5.0.7 on 2024-08-11 15:12

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quack_app', '0012_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='profile_pics/profile_default.jpg', upload_to='profile_pictures/'),
        ),
    ]
