# Generated by Django 5.0.7 on 2024-08-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quack_app', '0013_remove_user_username_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
