# Generated by Django 5.0.7 on 2024-08-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quack_app', '0016_user_is_tester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_tester',
        ),
    ]
